# Generated by Django 5.2.1 on 2025-05-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_options_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='questions',
            field=models.URLField(blank=True, null=True, verbose_name='Куда переводить при кнопке "Задать вопрос по Авто"? '),
        ),
    ]
