# Generated by Django 5.2.1 on 2025-05-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='carad',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_image',
            field=models.ImageField(upload_to='cars/', verbose_name='Загрузите фото'),
        ),
    ]
