# Generated by Django 5.2.1 on 2025-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0002_alter_carad_options_carad_slug_alter_carad_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
