# Generated by Django 5.2.1 on 2025-05-20 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0003_alter_carad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='car_engine_volume',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='car_month',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='carad',
            name='car_transmission',
            field=models.CharField(choices=[('Автомат (все типы)', 'Автомат (все типы)'), ('Вариатор', 'Вариатор'), ('Другое', 'Другое'), ('Полуавтоматическая', 'Полуавтоматическая'), ('Ручная', 'Ручная')], null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_color',
            field=models.CharField(choices=[('Белый', 'Белый'), ('Белый двухтонный', 'Белый двухтонный'), ('Бирюзовый', 'Бирюзовый'), ('Галактический серый', 'Галактический серый'), ('Желто-золотой', 'Желто-золотой'), ('Желтый', 'Желтый'), ('Жемчужный', 'Жемчужный'), ('Жемчужный двухтонный', 'Жемчужный двухтонный'), ('Зеленый', 'Зеленый'), ('Золотой', 'Золотой'), ('Золотой двухтонный', 'Золотой двухтонный'), ('Коричневый', 'Коричневый'), ('Коричневый двухтонный', 'Коричневый двухтонный'), ('Красный', 'Красный'), ('Лаймовый', 'Лаймовый'), ('Не определен', 'Не определен'), ('Небесно-голубой', 'Небесно-голубой'), ('Розовый', 'Розовый'), ('Серебристо-серый', 'Серебристо-серый'), ('Серебристый-двухтонный', 'Серебристый-двухтонный'), ('Серебряный', 'Серебряный'), ('Серый', 'Серый'), ('Синий', 'Синий'), ('Сиреневый', 'Сиреневый'), ('Темно-зеленый', 'Темно-зеленый'), ('Темно-серый', 'Темно-серый'), ('Темно-черный', 'Темно-черный'), ('Тростниковый', 'Тростниковый'), ('Фиолетовый', 'Фиолетовый'), ('Черный', 'Черный'), ('Черный двухтонный', 'Черный двухтонный'), ('Яркий серебристый', 'Яркий серебристый')], null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Бензин + Сжиженный газ', 'Бензин + Сжиженный газ'), ('Бензин + Сжиженный природный газ', 'Бензин + Сжиженный природный газ'), ('Бензин + Электричество', 'Бензин + Электричество'), ('Водород', 'Водород'), ('Дизель', 'Дизель'), ('Дизель + электричество', 'Дизель + электричество'), ('Не определено', 'Не определено'), ('Сжиженный газ', 'Сжиженный газ'), ('Электричество', 'Электричество')], null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
