# Generated by Django 5.2.1 on 2025-05-20 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0004_carad_car_engine_volume_carad_car_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='car_brand',
            field=models.CharField(choices=[('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('Benz (Mercedes-Benz)', 'Benz (Mercedes-Benz)'), ('BMW', 'BMW'), ('Book Ki Eun Award', 'Book Ki Eun Award'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chevrolet (GM Daewoo)', 'Chevrolet (GM Daewoo)'), ('Chrysler', 'Chrysler'), ('Citroen / DS', 'Citroen / DS'), ('Daihatsu', 'Daihatsu'), ('Dodge', 'Dodge'), ('Dongfeng', 'Dongfeng'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Folstar', 'Folstar'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infinity', 'Infinity'), ('Isuzu', 'Isuzu'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Matsuda', 'Matsuda'), ('McLaren', 'McLaren'), ('Mini', 'Mini'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Renault', 'Renault'), ('Renault-Korea', 'Renault-Korea'), ('Rolls-Royce', 'Rolls-Royce'), ('Smart', 'Smart'), ('Ssangyong', 'Ssangyong'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Прочие бренды', 'Прочие бренды'), ('Other imported cars', 'Other imported cars')], null=True, verbose_name='Марка '),
        ),
        migrations.AddField(
            model_name='carad',
            name='car_model',
            field=models.CharField(max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_color',
            field=models.CharField(choices=[('Белый', 'Белый'), ('Белый двухтонный', 'Белый двухтонный'), ('Бирюзовый', 'Бирюзовый'), ('Галактический серый', 'Галактический серый'), ('Желто-золотой', 'Желто-золотой'), ('Желтый', 'Желтый'), ('Жемчужный', 'Жемчужный'), ('Жемчужный двухтонный', 'Жемчужный двухтонный'), ('Зеленый', 'Зеленый'), ('Золотой', 'Золотой'), ('Золотой двухтонный', 'Золотой двухтонный'), ('Коричневый', 'Коричневый'), ('Коричневый двухтонный', 'Коричневый двухтонный'), ('Красный', 'Красный'), ('Лаймовый', 'Лаймовый'), ('Не определен', 'Не определен'), ('Небесно-голубой', 'Небесно-голубой'), ('Розовый', 'Розовый'), ('Серебристо-серый', 'Серебристо-серый'), ('Серебристый-двухтонный', 'Серебристый-двухтонный'), ('Серебряный', 'Серебряный'), ('Серый', 'Серый'), ('Синий', 'Синий'), ('Сиреневый', 'Сиреневый'), ('Темно-зеленый', 'Темно-зеленый'), ('Темно-серый', 'Темно-серый'), ('Темно-черный', 'Темно-черный'), ('Тростниковый', 'Тростниковый'), ('Фиолетовый', 'Фиолетовый'), ('Черный', 'Черный'), ('Черный двухтонный', 'Черный двухтонный'), ('Яркий серебристый', 'Яркий серебристый')], null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_engine_volume',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Бензин + Сжиженный газ', 'Бензин + Сжиженный газ'), ('Бензин + Сжиженный природный газ', 'Бензин + Сжиженный природный газ'), ('Бензин + Электричество', 'Бензин + Электричество'), ('Водород', 'Водород'), ('Дизель', 'Дизель'), ('Дизель + электричество', 'Дизель + электричество'), ('Не определено', 'Не определено'), ('Сжиженный газ', 'Сжиженный газ'), ('Электричество', 'Электричество')], null=True, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_mileage',
            field=models.PositiveIntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_month',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц выпуска '),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_name',
            field=models.CharField(max_length=255, verbose_name='Название '),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_transmission',
            field=models.CharField(choices=[('Автомат (все типы)', 'Автомат (все типы)'), ('Вариатор', 'Вариатор'), ('Другое', 'Другое'), ('Полуавтоматическая', 'Полуавтоматическая'), ('Ручная', 'Ручная')], null=True, verbose_name='Трансмиссия'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='car_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска '),
        ),
    ]
