# Generated by Django 5.2.1 on 2025-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0005_carad_car_brand_carad_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='car_generation',
            field=models.CharField(max_length=255, null=True, verbose_name='Поколение'),
        ),
    ]
