# Generated by Django 5.2.1 on 2025-05-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0006_carad_car_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='car_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_engine_volume',
            new_name='engine_volume',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_fuel',
            new_name='fuel',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_generation',
            new_name='generation',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_transmission',
            new_name='transmission',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='car_year',
            new_name='year',
        ),
    ]
