# Generated by Django 5.2.1 on 2025-05-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0007_rename_car_brand_carad_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='fuel',
            new_name='fuel_type',
        ),
    ]
