# Generated by Django 5.2.1 on 2025-05-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0008_rename_fuel_carad_fuel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='engine_volume',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='image',
            new_name='main_photo',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='carad',
            name='name',
        ),
        migrations.AddField(
            model_name='carad',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название '),
        ),
    ]
