# Generated by Django 5.2.1 on 2025-05-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0009_rename_engine_volume_carad_engine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='title',
            new_name='name',
        ),
    ]
