# Generated by Django 5.2.1 on 2025-05-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0010_rename_title_carad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название '),
        ),
    ]
