# Generated by Django 5.2.1 on 2025-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0011_alter_carad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='engine',
            field=models.FloatField(null=True, verbose_name='Объём двигателя'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
