# Generated by Django 5.2.1 on 2025-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0013_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='body_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='carad',
            name='inspection_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Дата инспекции'),
        ),
        migrations.AddField(
            model_name='carad',
            name='vin',
            field=models.CharField(max_length=255, null=True, verbose_name='VIN - код'),
        ),
    ]
