# Generated by Django 5.2.1 on 2025-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0014_carad_body_type_carad_inspection_date_carad_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='gen',
            field=models.CharField(max_length=255, null=True, verbose_name='Комплектация'),
        ),
        migrations.AddField(
            model_name='carad',
            name='warranty',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Гарантия'),
        ),
    ]
