# Generated by Django 5.2.1 on 2025-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0015_carad_gen_carad_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='option_1_1',
            field=models.BooleanField(default=False, null=True, verbose_name='Люк'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_10',
            field=models.BooleanField(default=False, null=True, verbose_name='Переключение передач веслами'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_11',
            field=models.BooleanField(default=False, verbose_name='Пульт дистанционного управления на рулевом колесе'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_12',
            field=models.BooleanField(default=False, null=True, verbose_name='Зеркало в комнате КСМ'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_13',
            field=models.BooleanField(default=False, null=True, verbose_name='Высокий проход'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_14',
            field=models.BooleanField(default=False, null=True, verbose_name='Электропривод дверного замка'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_15',
            field=models.BooleanField(default=False, null=True, verbose_name='Усилитель руля'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_16',
            field=models.BooleanField(default=False, null=True, verbose_name='Электрические окна'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_2',
            field=models.BooleanField(default=False, null=True, verbose_name='Головная лампа (светодиод)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_3',
            field=models.BooleanField(default=False, null=True, verbose_name='Электрический багажник с электроприводом'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_4',
            field=models.BooleanField(default=False, null=True, verbose_name='Призрачное закрытие двери'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_5',
            field=models.BooleanField(default=False, null=True, verbose_name='Электропривод складывающихся боковых зеркал'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_6',
            field=models.BooleanField(default=False, null=True, verbose_name='Алюминиевые диски'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_7',
            field=models.BooleanField(default=False, null=True, verbose_name='Багажник на крыше'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_8',
            field=models.BooleanField(default=False, null=True, verbose_name='Подогрев руля'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_1_9',
            field=models.BooleanField(default=False, null=True, verbose_name='Электропривод рулевого колеса'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_1',
            field=models.BooleanField(default=False, null=True, verbose_name='Подушка безопасности (сиденье водителя, сиденье пассажира)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_10',
            field=models.BooleanField(default=False, null=True, verbose_name='Датчик парковки (передний, задний)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_11',
            field=models.BooleanField(default=False, null=True, verbose_name='Система предупреждения о боковом столкновении сзади'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_12',
            field=models.BooleanField(default=False, null=True, verbose_name='Задняя камера'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_13',
            field=models.BooleanField(default=False, null=True, verbose_name='Обзор на 360 градусов'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_2',
            field=models.BooleanField(default=False, null=True, verbose_name='Подушка безопасности (боковая)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_3',
            field=models.BooleanField(default=False, null=True, verbose_name='Подушка безопасности (шторка)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_4',
            field=models.BooleanField(default=False, null=True, verbose_name='Антиблокировочная система тормозов (ABS)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_5',
            field=models.BooleanField(default=False, null=True, verbose_name='Противоскользящее покрытие (TCS)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_6',
            field=models.BooleanField(default=False, null=True, verbose_name='Электронная система контроля устойчивости (ESC)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_7',
            field=models.BooleanField(default=False, null=True, verbose_name='Датчик давления в шинах (TPMS)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_8',
            field=models.BooleanField(default=False, null=True, verbose_name='Система предупреждения о выезде с полосы движения (LDWS)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_2_9',
            field=models.BooleanField(default=False, null=True, verbose_name='Поддержка с электронным управлением (ECS)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_1',
            field=models.BooleanField(default=False, null=True, verbose_name='Круиз-контроль (обычный, адаптивный)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_10',
            field=models.BooleanField(default=False, null=True, verbose_name='Навигация'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_11',
            field=models.BooleanField(default=False, null=True, verbose_name='AV-монитор на переднем сиденье'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_12',
            field=models.BooleanField(default=False, null=True, verbose_name='AV-монитор на заднем сиденье'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_13',
            field=models.BooleanField(default=False, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_14',
            field=models.BooleanField(default=False, null=True, verbose_name='CD-плеер'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_15',
            field=models.BooleanField(default=False, null=True, verbose_name='USB-порт'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_16',
            field=models.BooleanField(default=False, null=True, verbose_name='AUX-приемник'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_2',
            field=models.BooleanField(default=False, null=True, verbose_name='Проекционный дисплей (HUD)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_3',
            field=models.BooleanField(default=False, null=True, verbose_name='Электронный стояночный тормоз (EPB)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_4',
            field=models.BooleanField(default=False, null=True, verbose_name='Автоматическое кондиционирование воздуха'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_5',
            field=models.BooleanField(default=False, null=True, verbose_name='Смарт-ключ'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_6',
            field=models.BooleanField(default=False, null=True, verbose_name='Беспроводной дверной замок'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_7',
            field=models.BooleanField(default=False, null=True, verbose_name='Датчик дождя'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_8',
            field=models.BooleanField(default=False, null=True, verbose_name='Автоматический свет'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_3_9',
            field=models.BooleanField(default=False, null=True, verbose_name='Шторка/жалюзи (заднее сиденье, сзади)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_1',
            field=models.BooleanField(default=False, null=True, verbose_name='Кожаные сиденья'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_2',
            field=models.BooleanField(default=False, null=True, verbose_name='Электропривод сидений (водительское сиденье, пассажирское сиденье)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_3',
            field=models.BooleanField(default=False, null=True, verbose_name='Электропривод сидений (задние сиденья)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_4',
            field=models.BooleanField(default=False, null=True, verbose_name='Подогрев сидений (передних и задних)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_5',
            field=models.BooleanField(default=False, null=True, verbose_name='Сиденья с памятью (водительское сиденье, пассажирское сиденье)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_6',
            field=models.BooleanField(default=False, null=True, verbose_name='Вентилируемые сиденья (водительское сиденье, пассажирское сиденье)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_7',
            field=models.BooleanField(default=False, null=True, verbose_name='Вентилируемые сиденья (задние сиденья)'),
        ),
        migrations.AddField(
            model_name='carad',
            name='option_5_8',
            field=models.BooleanField(default=False, null=True, verbose_name='Массажная простыня'),
        ),
    ]
