# Generated by Django 5.2.1 on 2025-06-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0016_carad_option_1_1_carad_option_1_10_carad_option_1_11_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_1',
            new_name='option_4_1',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_2',
            new_name='option_4_2',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_3',
            new_name='option_4_3',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_4',
            new_name='option_4_4',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_5',
            new_name='option_4_5',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_6',
            new_name='option_4_6',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_7',
            new_name='option_4_7',
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='option_5_8',
            new_name='option_4_8',
        ),
    ]
