# Generated by Django 4.2.13 on 2025-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0017_rename_option_5_1_carad_option_4_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='brand',
            field=models.CharField(choices=[('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('Benz (Mercedes-Benz)', 'Benz (Mercedes-Benz)'), ('BMW', 'BMW'), ('Book Ki Eun Award', 'Book Ki Eun Award'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chevrolet (GM Daewoo)', 'Chevrolet (GM Daewoo)'), ('Chrysler', 'Chrysler'), ('Citroen / DS', 'Citroen / DS'), ('Daihatsu', 'Daihatsu'), ('Dodge', 'Dodge'), ('Dongfeng', 'Dongfeng'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Folstar', 'Folstar'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infinity', 'Infinity'), ('Isuzu', 'Isuzu'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Matsuda', 'Matsuda'), ('McLaren', 'McLaren'), ('Mini', 'Mini'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Renault', 'Renault'), ('Renault-Korea', 'Renault-Korea'), ('Rolls-Royce', 'Rolls-Royce'), ('Smart', 'Smart'), ('Ssangyong', 'Ssangyong'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Прочие бренды', 'Прочие бренды'), ('Other imported cars', 'Other imported cars')], max_length=255, null=True, verbose_name='Марка '),
        ),
        migrations.AlterField(
            model_name='carad',
            name='color',
            field=models.CharField(choices=[('Белый', 'Белый'), ('Белый двухтонный', 'Белый двухтонный'), ('Бирюзовый', 'Бирюзовый'), ('Галактический серый', 'Галактический серый'), ('Желто-золотой', 'Желто-золотой'), ('Желтый', 'Желтый'), ('Жемчужный', 'Жемчужный'), ('Жемчужный двухтонный', 'Жемчужный двухтонный'), ('Зеленый', 'Зеленый'), ('Золотой', 'Золотой'), ('Золотой двухтонный', 'Золотой двухтонный'), ('Коричневый', 'Коричневый'), ('Коричневый двухтонный', 'Коричневый двухтонный'), ('Красный', 'Красный'), ('Лаймовый', 'Лаймовый'), ('Не определен', 'Не определен'), ('Небесно-голубой', 'Небесно-голубой'), ('Розовый', 'Розовый'), ('Серебристо-серый', 'Серебристо-серый'), ('Серебристый-двухтонный', 'Серебристый-двухтонный'), ('Серебряный', 'Серебряный'), ('Серый', 'Серый'), ('Синий', 'Синий'), ('Сиреневый', 'Сиреневый'), ('Темно-зеленый', 'Темно-зеленый'), ('Темно-серый', 'Темно-серый'), ('Темно-черный', 'Темно-черный'), ('Тростниковый', 'Тростниковый'), ('Фиолетовый', 'Фиолетовый'), ('Черный', 'Черный'), ('Черный двухтонный', 'Черный двухтонный'), ('Яркий серебристый', 'Яркий серебристый')], max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Бензин + Сжиженный газ', 'Бензин + Сжиженный газ'), ('Бензин + Сжиженный природный газ', 'Бензин + Сжиженный природный газ'), ('Бензин + Электричество', 'Бензин + Электричество'), ('Водород', 'Водород'), ('Дизель', 'Дизель'), ('Дизель + электричество', 'Дизель + электричество'), ('Не определено', 'Не определено'), ('Сжиженный газ', 'Сжиженный газ'), ('Электричество', 'Электричество')], max_length=255, null=True, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='option_1_11',
            field=models.BooleanField(default=False, null=True, verbose_name='Пульт дистанционного управления на рулевом колесе'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='transmission',
            field=models.CharField(choices=[('Автомат (все типы)', 'Автомат (все типы)'), ('Вариатор', 'Вариатор'), ('Другое', 'Другое'), ('Полуавтоматическая', 'Полуавтоматическая'), ('Ручная', 'Ручная')], max_length=255, null=True, verbose_name='Трансмиссия'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='warranty',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=255, null=True, verbose_name='Гарантия'),
        ),
    ]
